### ISSUE TITLE
Error-free reads?

### ISSUE THREAD

**Issue by teojcryan** [metagenlab/MeSS#32]
Hi, again thank you for developing `MeSS` - it's been very helpful in my work thus far.

Apologies if this is already quite clear, but I wanted to know if there is a way to generate reads without sequencing error? I need to create a control to compare between error-free reads and reads with different error profiles.

I'm not sure if the BAM file from the `--bam` option with `mess run` refers to this, but being able to have the error-free SAM file from `art_illumina` with the [--errfree](https://manpages.debian.org/testing/art-nextgen-simulation-tools/art_illumina.1.en.html#ef) argument would be very helpful. Thanks!

**Comment by teojcryan** [comment]
I've tried to extend the current code to output the error-free BAM file [here](https://github.com/metagenlab/MeSS/compare/dev...teojcryan:MeSS:dev). As of now it successfully outputs separate .bam files in a "ef" folder, but it seems like they are identical to the .bam files in the "bam" folder so something went wrong somewhere (I'm not too familiar with Snakemake). I hope this is helpful somehow!

**Comment by farchaab** [comment]
Hello @teojcryan, thank you again for using `MeSS`, much appreciate it !

Currently, `MeSS` only generates bam files with sequencing errors with the `--bam` option. It should be trivial to add this function, since we only need to add the `--errfree` flag for `art_illumina`.

I am looking at your branch, glad that it worked for you !

If you want you can open a pull request and we can implement the changes in a next release !
